version: "3.9"

services:
  backend:
    build: ./backend
    container_name: ftth-backend
    environment:
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=8000
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  frontend:
    build: ./frontend
    container_name: ftth-frontend
    environment:
      - VITE_BACKEND_URL=http://localhost:8000
      - FRONTEND_PORT=5173
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/usr/src/app
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    depends_on:
      - backend
