version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ftth-backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ftth-frontend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: ftth-db
    restart: always
    environment:
      POSTGRES_USER: ftth_user
      POSTGRES_PASSWORD: ftth_pass
      POSTGRES_DB: ftth_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
